version: '3.8'

services:
  db:
    restart: always
    image: mysql/mysql-server:8.0
    container_name: mlflow_db
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
        
  frauddetectionapp:
    image: frauddetection:v1
    ports:
      - "8501:8501"
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    ports:
      - "8080:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./mlruns.db:/app/mlruns.db
    # command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow_bucket/mlflow/ --host 0.0.0.0
    command: mlflow server --backend-store-uri ${MLFOW_TRACKING_URI_MYSQL} --default-artifact-root s3://frauddbucket/mlflow/ --host 0.0.0.0

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  artifacts:
  logs:
  dbdata:
  mlruns:
